name: Execute tests with gradle 
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            ref: ${{ github.ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute tests with Gradle
        run: ./gradlew test
